# Basic Info
basic_config: {
  experiment_name: "toy_dataset",
  experiment_performer: "yiyuanyang",
  experiment_date: "2020-06-04",
}


# Data Loading
data_config: {
  train_csv: "C:\\Users\\yangy\\Documents\\ComputerVision\\Projects\\code\\projects\\Evolution\\data\\shape\\toy_dataset\\train.csv",
  eval_csv: "C:\\Users\\yangy\\Documents\\ComputerVision\\Projects\\code\\projects\\Evolution\\data\\shape\\toy_dataset\\eval.csv",
  test_csv: C:\\Users\\yangy\\Documents\\ComputerVision\\Projects\\code\\projects\\Evolution\\data\\shape\\toy_dataset\\test.csv",
  in_channels: 1,
  image_size: 128,
  num_classes: 14,
  data_loader_params: {
    shuffle: True,
    num_workers: 8,
    batch_size: 20
  }
}


# Training
train_config: {
  model_config: {
    model_type: "resnet18",
    in_channels: 1,
    image_size: 128,
    num_classes: 14,
    kernel_sizes: [7,3,3,3,3]
  },
  learning_config: {
    start_epoch: 1, # ** If restart, change this 
    max_epoch: 100,
    use_existing_model: False, # ** If restart, change this
    learning_rate: 0.01,
    eval_only: False,
    adjust_lr: False,
    # gamma: 0.98,
    loss: "cross_entropy",
    gradient_clip: False,
    gradient_clip_value: 1
  }
}


# Logger and model saving
save_config: {
  save_dir: "E:\\saved_experiments\\exp004\\shape_project", 
  use_logger: True,
  dump_frequency: 1,
  log_frequency: 200,
  display_frequency: 1000
}
