# Basic Info
experiment_name: "exp001_gradient_descent"
experiment_performer: "yiyuanyang"
experiment_date: "2020-04-16"

# Data Loading
data_directory: ""

# Training
model_settings: {
  model_type: "ResNet",
  num_layers: 18
}

# Model Saving
model_directory: ""
