# Basic Info
basic_config: {
  experiment_name: "exp001_gradient_descent_2",
  experiment_performer: "yiyuanyang",
  experiment_date: "2020-04-24",
}

# Data Loading
data_config: {
  data_dir: "D:\\datasets\\cifar-10",
  train_data: [
    "data_batch_1",
    "data_batch_2",
    "data_batch_3",
    "data_batch_4"
  ],
  eval_data: ["data_batch_5"],
  test_data: ["test_batch"],
  in_channels: 3,
  image_size: 32,
  num_classes: 10,
  data_loader_params: {
    shuffle: True,
    num_workers: 8,
    batch_size: 80
  }
}

# Training
train_config: {
  model_config: {
    model_type: "resnet10",
    in_channels: 3,
    image_size: 32,
    num_classes: 10
  },
  learning_config: {
    start_epoch: 1,
    max_epoch: 150,
    use_existing_model: False,
    adjust_learning_rate: True,
    learning_rate: 0.05,
    eval_only: False,
    adjust_lr: True,
    steps: [30,60,90,120,150],
    gamma: 0.7,
    loss: "cross_entropy",
    gradient_clip: False,
    gradient_clip_value: 1
  }
}

# Logger and model saving
save_config: {
  save_dir: "E:\\saved_experiments\\evolution", 
  use_logger: True,
  dump_frequency: 10,
  log_frequency: 200,
  display_frequency: 1000
}
