# Basic Info
basic_config: {
  experiment_name: "exp001_gradient_descent",
  experiment_performer: "yiyuanyang",
  experiment_date: "2020-04-16"
}

# Data Loading
data_config: {
  data_directory: ""
}

# Training
model_config: {
  model_type: ResNet,
  num_layers: 18,
  kernel_size: 3,
  stride: 1,
  padding: 1
}

# Model Saving
save_config: {
  model_directory: "",
  logs_directory: ""
}