# Basic Info
basic_config: {
  experiment_name: "15_class_normal_size",
  experiment_performer: "yiyuanyang",
  experiment_date: "2020-06-24",
}


# Data Loading
data_config: {
  path_to_labels_dir: "C:\\Users\\yangy\\Documents\\ComputerVision\\Projects\\code\\projects\\Evolution\\data\\quickdraw\\15_class_normal_size", 
  data_loader_params: {
    shuffle: True,
    num_workers: 8,
    batch_size: 20
  }
}


# Training
train_config: {
  model_config: {
    model_type: "resnet18",
    kernel_sizes: [7,3,3,3,3],
    layer_save_config: {
      layer_save_dir: "",
      epochs_per_save: 10
    }
  },
  learning_config: {
    start_epoch: 1, # ** If restart, change this 
    max_epoch: 100,
    use_existing_model: False, # ** If restart, change this
    learning_rate: 0.01,
    eval_only: False,
    adjust_lr: False,
    # gamma: 0.98,
    loss: "cross_entropy",
    gradient_clip: False,
    gradient_clip_value: 1
  }
}


# Logger and model saving
save_config: {
  save_dir: "E:\\saved_experiments\\exp005\\quickdraw", 
  use_logger: True,
  dump_frequency: 1,
  log_frequency: 200,
  display_frequency: 1000
}
